In [49]:
import pandas as pd 
import helpers
import re

In [50]:
path = "../Data/output/preprocessing_base.csv"
df = pd.read_csv(path)
df.head()

,Restaurant,Review,Rating,Edited_Review,language
0,Beyond Flavours,"The ambience was good, food was quite good . h...",5,"The ambience was good, food was quite good . h...",en
1,Beyond Flavours,Ambience is too good for a pleasant evening. S...,5,Ambience is too good for a pleasant evening. S...,en
2,Beyond Flavours,A must try.. great food great ambience. Thnx f...,5,A must try.. great food great ambience. Thnx f...,en
3,Beyond Flavours,Soumen das and Arun was a great guy. Only beca...,5,Soumen das and Arun was a great guy. Only beca...,en
4,Beyond Flavours,Food is good.we ordered Kodi drumsticks and ba...,5,Food is good.we ordered Kodi drumsticks and ba...,en

In [51]:
df['Edited_Review'] = df['Edited_Review'].str.lower()
df

,Restaurant,Review,Rating,Edited_Review,language
0,Beyond Flavours,"The ambience was good, food was quite good . h...",5,"the ambience was good, food was quite good . h...",en
1,Beyond Flavours,Ambience is too good for a pleasant evening. S...,5,ambience is too good for a pleasant evening. s...,en
2,Beyond Flavours,A must try.. great food great ambience. Thnx f...,5,a must try.. great food great ambience. thnx f...,en
3,Beyond Flavours,Soumen das and Arun was a great guy. Only beca...,5,soumen das and arun was a great guy. only beca...,en
4,Beyond Flavours,Food is good.we ordered Kodi drumsticks and ba...,5,food is good.we ordered kodi drumsticks and ba...,en
...,...,...,...,...,...
8978,Chinese Pavilion,Madhumathi Mahajan Well to start with nice cou...,3,madhumathi mahajan well to start with nice cou...,en
8979,Chinese Pavilion,This place has never disappointed us.. The foo...,4.5,this place has never disappointed us.. the foo...,en
8980,Chinese Pavilion,"Bad rating is mainly because of ""Chicken Bone ...",1.5,"bad rating is mainly because of ""chicken bone ...",en
8981,Chinese Pavilion,I personally love and prefer Chinese Food. Had...,4,i personally love and prefer chinese food. had...,en
8982,Chinese Pavilion,Checked in here to try some delicious chinese ...,3.5,checked in here to try some delicious chinese ...,en

In [52]:
df['Edited_Review'] = df['Edited_Review'].apply(helpers.detect_smiley)
df

,Restaurant,Review,Rating,Edited_Review,language
0,Beyond Flavours,"The ambience was good, food was quite good . h...",5,"the ambience was good, food was quite good . h...",en
1,Beyond Flavours,Ambience is too good for a pleasant evening. S...,5,ambience is too good for a pleasant evening. s...,en
2,Beyond Flavours,A must try.. great food great ambience. Thnx f...,5,a must try.. great food great ambience. thnx f...,en
3,Beyond Flavours,Soumen das and Arun was a great guy. Only beca...,5,soumen das and arun was a great guy. only beca...,en
4,Beyond Flavours,Food is good.we ordered Kodi drumsticks and ba...,5,food is good.we ordered kodi drumsticks and ba...,en
...,...,...,...,...,...
8978,Chinese Pavilion,Madhumathi Mahajan Well to start with nice cou...,3,madhumathi mahajan well to start with nice cou...,en
8979,Chinese Pavilion,This place has never disappointed us.. The foo...,4.5,this place has never disappointed us.. the foo...,en
8980,Chinese Pavilion,"Bad rating is mainly because of ""Chicken Bone ...",1.5,"bad rating is mainly because of ""chicken bone ...",en
8981,Chinese Pavilion,I personally love and prefer Chinese Food. Had...,4,i personally love and prefer chinese food. had...,en
8982,Chinese Pavilion,Checked in here to try some delicious chinese ...,3.5,checked in here to try some delicious chinese ...,en

In [53]:
df['Edited_Review'] = df['Edited_Review'].apply(helpers.replace_emoji)
df['Edited_Review']

0       the ambience was good, food was quite good . h...
1       ambience is too good for a pleasant evening. s...
2       a must try.. great food great ambience. thnx f...
3       soumen das and arun was a great guy. only beca...
4       food is good.we ordered kodi drumsticks and ba...
                              ...
8978    madhumathi mahajan well to start with nice cou...
8979    this place has never disappointed us.. the foo...
8980    bad rating is mainly because of "chicken bone ...
8981    i personally love and prefer chinese food. had...
8982    checked in here to try some delicious chinese ...
Name: Edited_Review, Length: 8983, dtype: object

In [54]:
df['Edited_Review'] = df['Edited_Review'].str.replace(r'\s+', ' ', regex=True)
df['Edited_Review']

0       the ambience was good, food was quite good . h...
1       ambience is too good for a pleasant evening. s...
2       a must try.. great food great ambience. thnx f...
3       soumen das and arun was a great guy. only beca...
4       food is good.we ordered kodi drumsticks and ba...
                              ...
8978    madhumathi mahajan well to start with nice cou...
8979    this place has never disappointed us.. the foo...
8980    bad rating is mainly because of "chicken bone ...
8981    i personally love and prefer chinese food. had...
8982    checked in here to try some delicious chinese ...
Name: Edited_Review, Length: 8983, dtype: object

In [55]:
''' 
nltk.download('stopwords')
nltk.download('punkt_tab')

stop_words = set(stopwords.words('english'))

negation_words = {
    "not", "never", "no", "nor", "n't", "none", "nobody", "nothing", "nowhere",
    "neither", "hardly", "scarcely", "rarely", "seldom", "few", "without", 
    "lack", "little", "less", "against", "minus"
}
stop_words = stop_words - negation_words

filtered_reviews = []

for idx, value in enumerate(df['Edited_Review']):
    word_tokens = word_tokenize(value) 
    filtered_sentence = [w for w in word_tokens if not w.lower() in stop_words]
    filtered_sentence_str = ' '.join(filtered_sentence)
    filtered_reviews.append(filtered_sentence_str)

df['Edited_Review'] = filtered_reviews
'''

' \nnltk.download(\'stopwords\')\nnltk.download(\'punkt_tab\')\n\nstop_words = set(stopwords.words(\'english\'))\n\nnegation_words = {\n    "not", "never", "no", "nor", "n\'t", "none", "nobody", "nothing", "nowhere",\n    "neither", "hardly", "scarcely", "rarely", "seldom", "few", "without", \n    "lack", "little", "less", "against", "minus"\n}\nstop_words = stop_words - negation_words\n\nfiltered_reviews = []\n\nfor idx, value in enumerate(df[\'Edited_Review\']):\n    word_tokens = word_tokenize(value) \n    filtered_sentence = [w for w in word_tokens if not w.lower() in stop_words]\n    filtered_sentence_str = \' \'.join(filtered_sentence)\n    filtered_reviews.append(filtered_sentence_str)\n\ndf[\'Edited_Review\'] = filtered_reviews\n'

In [56]:
df['Edited_Review']

0       the ambience was good, food was quite good . h...
1       ambience is too good for a pleasant evening. s...
2       a must try.. great food great ambience. thnx f...
3       soumen das and arun was a great guy. only beca...
4       food is good.we ordered kodi drumsticks and ba...
                              ...
8978    madhumathi mahajan well to start with nice cou...
8979    this place has never disappointed us.. the foo...
8980    bad rating is mainly because of "chicken bone ...
8981    i personally love and prefer chinese food. had...
8982    checked in here to try some delicious chinese ...
Name: Edited_Review, Length: 8983, dtype: object

In [57]:
def add_space_after_punctuation(text):
    text = re.sub(r'(?<!\.)\.(?!\.)|(?<!\!)\!(?!\!)|(?<!\?)\?(?!\?)|(?<!\,)\,(?!\,)|(?<!\;)\;(?!\;)|(?<!\:)\:(?!\:)', r'\g<0> ', text)
    text = re.sub(r'(\.{2,}|\!{2,}|\?{2,})', r'\1 ', text)
    
    return text

df['Edited_Review'] = df['Edited_Review'].apply(add_space_after_punctuation)

In [58]:
'''
import re
def clean_text_preserve_apostrophes(text): # Kesme iÅŸaretlerini koruyarak diÄŸer noktalama iÅŸaretlerini kaldÄ±r
    text = re.sub(r"[^\w\s']", " ", text)  # Harfler, rakamlar, boÅŸluklar ve kesme iÅŸareti dÄ±ÅŸÄ±ndaki karakterleri kaldÄ±r
    text = re.sub(r"\s+", " ", text)       # Birden fazla boÅŸluÄŸu tek boÅŸluÄŸa indir
    return text.strip()

edited_strings = []
for value in df['Edited_Review']:
    cleaned_value = clean_text_preserve_apostrophes(value)
    edited_strings.append(cleaned_value)

df['Edited_Review'] = edited_strings
df['Edited_Review']
'''

<>:1: SyntaxWarning: invalid escape sequence '\w'
<>:1: SyntaxWarning: invalid escape sequence '\w'
/var/folders/6m/ym3_2fk172zf4t8bql8zbq_w0000gn/T/ipykernel_6476/1364135369.py:1: SyntaxWarning: invalid escape sequence '\w'
  '''

'\nimport re\ndef clean_text_preserve_apostrophes(text): # Kesme iÅŸaretlerini koruyarak diÄŸer noktalama iÅŸaretlerini kaldÄ±r\n    text = re.sub(r"[^\\w\\s\']", " ", text)  # Harfler, rakamlar, boÅŸluklar ve kesme iÅŸareti dÄ±ÅŸÄ±ndaki karakterleri kaldÄ±r\n    text = re.sub(r"\\s+", " ", text)       # Birden fazla boÅŸluÄŸu tek boÅŸluÄŸa indir\n    return text.strip()\n\nedited_strings = []\nfor value in df[\'Edited_Review\']:\n    cleaned_value = clean_text_preserve_apostrophes(value)\n    edited_strings.append(cleaned_value)\n\ndf[\'Edited_Review\'] = edited_strings\ndf[\'Edited_Review\']\n'

In [59]:
df['Edited_Review'] = df['Edited_Review'].str.replace(r'\s+', ' ', regex=True)

In [60]:
df.to_csv("../Data/output/preproces_for_vader.csv", index=False)